import { writeFileSync, mkdirSync, appendFileSync } from "fs";
import { resolve } from "path";
import { stringify as stringifyYaml } from "yaml";
import { bookSchema } from "../books-schema";
import type { ErrorLogEntry } from "./types";

const OUTPUT_DIR = resolve(process.cwd(), "output/research");
const ERROR_LOG = resolve(OUTPUT_DIR, "_errors.log");

export function writeBookYaml(slug: string, bookData: Record<string, any>): boolean {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // Validate against schema before writing
  const validation = bookSchema.safeParse(bookData);
  if (!validation.success) {
    logError({
      timestamp: new Date().toISOString(),
      asin: bookData.workExample?.[0]?.asin || "UNKNOWN",
      type: "SCHEMA_FAIL",
      detail: validation.error.issues.map(i => `${i.path.join(".")}: ${i.message}`).join("; "),
    });
    return false;
  }

  const header = [
    `# Generated by research-book.ts at ${new Date().toISOString()}`,
    `# ASIN: ${bookData.workExample?.[0]?.asin || "N/A"}`,
    `# Sources: books.json, dirkwernerbooks.com (cached), Goodreads RSS, identity.yaml.apps`,
    `#`,
  ].join("\n");

  const yamlContent = stringifyYaml({ books: [bookData] });
  const output = `${header}\n${yamlContent}`;

  writeFileSync(resolve(OUTPUT_DIR, `${slug}.yaml`), output);
  return true;
}

export function logError(entry: ErrorLogEntry): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const line = `${entry.timestamp} | ${entry.asin} | ${entry.type} | ${entry.detail}\n`;
  appendFileSync(ERROR_LOG, line);
}

export interface IndexManifest {
  generatedAt: string;
  totalBooks: number;
  successCount: number;
  errorCount: number;
  goodreadsStats: {
    exact: number;
    isbn: number;
    fuzzy: number;
    unmatched: number;
    unmatchedAsins: string[];
  };
  appMatchStats: Record<string, number>;
  translationPairs: Array<{ de: string; en: string }>;
}

export function writeIndexManifest(manifest: IndexManifest): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const yamlContent = stringifyYaml(manifest);
  writeFileSync(resolve(OUTPUT_DIR, "_index.yaml"), yamlContent);
}
